### ISSUE TITLE
Vivaldi Web Brower Script Issue

### ISSUE THREAD

**Issue by spectrumcomputing** [dasgeekchannel/AutoInstallBashScripts#11]
Hi,

When I try and install Vivaldi with the script I get:

dpkg: error: cannot access archive 'vivaldi-stable_1.14.1077.55-1_amd64.deb': No such file or directory

PS - Thanks for Destination Linux. I love it!

**Comment by RiderExMachina** [comment]
That's because the latest version is at https://downloads.vivaldi.com/stable/vivaldi-stable_1.15.1147.64-1_amd64.deb

**Comment by dasgeekchannel** [comment]
Fixed, thanks for reporting the issue!
