### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by millerlight** [dasgeekchannel/AutoInstallBashScripts#12]
./installscript: line 509: unexpected EOF while looking for matching ``'
./installscript: line 638: syntax error: unexpected end of file

**Comment by Greyjacket** [comment]
Got the same error. Just commented it out and it ran afterwards.

**Comment by RiderExMachina** [comment]
I created a pull request to fix the issue. Just waiting on @dasgeekchannel to approve it.

**Comment by dasgeekchannel** [comment]
Approved
