### ISSUE TITLE
errors on kde neon 18.04

### ISSUE THREAD

**Issue by Skrappjaw** [dasgeekchannel/AutoInstallBashScripts#19]
> $ sudo ./installscript 
> install: invalid option -- 'y'
> Try 'install --help' for more information.
> ./installscript: line 13: update: command not found
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Entering ResolveByKeep 10%
> Calculating upgrade... Done
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> ./installscript: line 328: syntax error near unexpected token `do'
> ./installscript: line 328: `                                    do'
>

**Comment by RiderExMachina** [comment]
~~What shell are you using? Bash?~~

Never mind, the shell doesn't matter.
