### ISSUE TITLE
Add essential apps to the kxstudio/jack installer

### ISSUE THREAD

**Issue by Skrappjaw** [dasgeekchannel/AutoInstallBashScripts#3]
jack does not install on Ubuntu 18.04 unless you apt update && apt upgrade packages first. Then re-login.

>$ sudo apt  update && sudo apt upgrade -y
$ sudo apt install jackd2 carla-git non-mixer pulseaudio-module-jack cadence

**Comment by dasgeekchannel** [comment]
This has been fixed in the latest version
